export const data = {
  name: 'Gerson González',
  role: 'Front-End & UI/UX Developer',
  location: 'Heredia, Costa Rica',
  email: 'ggzmiranda@gmail.com',
  phone: '+506 7029 9050',
  github: 'https://github.com/ggnz',
  linkedin: 'https://www.linkedin.com/in/gerson-gonz%C3%A1lez-a52695266/',

  about: `Systems Engineer with a strong focus on front-end development and UI/UX implementation.
I translate design systems into production-ready applications using Vue and React, work hands-on in Figma from wireframe to handoff, and integrate AI tools into my development workflow to ship faster and smarter.
Through my work at AnalyticaHub, I've also gained hands-on exposure to BI and data analytics — working alongside data teams and contributing to projects involving Power BI dashboards, ETL pipelines, and data visualization.
`,

  experience: [
    {
      company: 'GPT Energytel S.A',
      role: 'Software Developer',
      period: 'Oct 2024 – Present',
      location: 'Costa Rica',
      highlights: [
        'Built CRM platform integrating Facebook, WhatsApp, and Instagram into one system',
        'Developed BPMS for project tracking, cost management, and performance monitoring',
        'Designed and deployed NIMBUS LMS with AWS CloudFront & S3 for video/file storage',
        'Implemented QR-based registration with interactive data visualization charts',
        'Maintained AWS infrastructure: RDS, S3, CloudFront, Buckets',
        'Collaborated with back-end teams using NestJS under agile methodology',
      ],
    },
    {
      company: 'AnalyticaHub',
      role: 'Front-End & UI/UX Developer (Freelance)',
      period: 'Jan 2026 – Present',
      location: 'Costa Rica',
      highlights: [
        'Designed UI/UX flows in Figma for e-commerce, CRM, landing pages, and chat platforms',
        'Implemented designs into Vue applications with pixel-accurate responsive results',
        'Delivered ccscomdata.com — full Figma-to-Vue implementation for tech products client',
        'Collaborated with data teams on BI projects, gaining exposure to Power BI dashboards and ETL pipelines',
        'Leveraged Claude and Stitch to accelerate development workflows',
      ],
    },
    {
      company: 'Escuela Los Ángeles',
      role: 'Programming Instructor',
      period: 'Mar 2022 – Jun 2024',
      location: 'Costa Rica',
      size: 'half',
      highlights: [
        'Designed and delivered weekly lessons on Python and Arduino',
        'Led hands-on coding projects strengthening students\' problem-solving skills',
      ],
    },
    {
      company: 'Popular Pensiones',
      role: 'IT Assistant (Internship)',
      period: 'Sep 2018 – Nov 2018',
      location: 'Costa Rica',
      size: 'half',
      highlights: [
        'Provided technical support via phone, email, and in-person channels',
        'Assisted with network configuration and troubleshooting for routers, switches, and connectivity',
      ],
    },
  ],

  projects: [
    {
      name: 'NIMBUS',
      description: 'LMS with three roles — Owner, Instructor, and Student. Instructors create courses with video lessons and graded quizzes. Students enroll, pay via Tilopay, complete courses, download files, and receive a certificate. Video streaming and file storage powered by AWS CloudFront and S3.',
      tags: ['Vue', 'NestJS', 'AWS', 'S3', 'CloudFront', 'Tilopay'],
      url: 'https://byhqqbrkne.us-west-2.awsapprunner.com',
      type: 'Work Project',
      images: ['lms1.png', 'lms2.png', 'lms3.png', 'lms4.png', 'lms5.png'],
    },
    {
      name: 'Business Project Management System',
      description: 'Internal BPMS for GPT Energytel. Projects and clients are created with linked tasks and opportunities tracked through a Kanban board, giving the company a clear view of progress, resource allocation, and cost control.',
      tags: ['Vue', 'NestJS', 'AWS', 'Figma'],
      url: '',
      type: 'Work Project',
      images: ['bpms1.png', 'bpms2.png', 'bpms3.png'],
    },
    {
      name: 'QR Registration System',
      description: 'Census-style data collection platform built for a GPT Energytel client. Users register via QR codes with reCAPTCHA validation and SMS verification. Supports bulk voter roll uploads, high-volume record management, and interactive dashboards for real-time data visualization.',
      tags: ['Vue', 'Chart.js', 'NestJS', 'reCAPTCHA', 'SMS'],
      url: '',
      type: 'Work Project',
      images: ['qr1.png', 'qr2.png', 'qr3.png'],
    },
    {
      name: 'CRM Platform',
      description: 'Unified CRM with a real-time inbox aggregating messages from Facebook, Instagram, and WhatsApp via the Meta API. WebSockets power live updates and reactivity. Includes full contact management with conversation history and status tracking.',
      tags: ['Vue', 'NestJS', 'Meta API', 'WebSockets'],
      url: '',
      type: 'Work Project',
      images: ['crm1.png', 'crm2.png', 'crm3.png', 'crm4.png'],
    },
    {
      name: 'SuperBaterias',
      description: 'Figma UI/UX design for a battery products e-commerce. Includes a product catalog, shopping cart, order tracking, brand showcase sections, and an appointment scheduling module.',
      tags: ['Figma', 'UI/UX', 'E-commerce'],
      url: '',
      type: 'Freelance',
      images: ['sb1.png', 'sb2.png', 'sb3.png', 'sb4.png'],
    },
    {
      name: 'CCS Comdata Services',
      description: 'Webflow CMS website for CCS Comdata showcasing their technology products and services. Built with a content-managed structure so the client can update offerings without touching code.',
      tags: ['Webflow', 'CMS', 'UI/UX'],
      url: 'https://www.ccscomdata.com',
      type: 'Freelance',
      images: ['CCS1.png', 'CCS2.png', 'CCS3.png'],
    },
    {
      name: 'Mi Crédito Fácil',
      description: 'Figma UI/UX design for a credit services company. Features a multi-step credit application form guiding users through service options and required documentation. Fully designed for desktop and mobile.',
      tags: ['Figma', 'UI/UX', 'Mobile'],
      url: '',
      type: 'Freelance',
      images: ['mcf1.png', 'mcf2.png', 'mcf3.png'],
    },  
    {
      name: 'AnalyticaHub',
      description: 'Landing page for AnalyticaHub, a data analytics and BI company. Features a modern hero section, services showcase, and a contact form for client inquiries — designed for conversion and built for desktop and mobile.',
      tags: ['Vue', 'Tailwind', 'Formspree', 'UI/UX', 'Landing Page'],
      url: 'https://www.analyticahub.com/',
      type: 'Freelance',
      images: ['analytica1.png', 'analytica2.png', 'analytica3.png', 'analytica4.png'],
    },
    {
      name: 'PMT',
      description: 'Figma UI/UX design covering company profile, services, and product offerings. Clean, modern layout designed for both desktop and mobile.',
      tags: ['Figma', 'UI/UX', 'Mobile'],
      url: '',
      type: 'Freelance',
      images: ['pmt1.png', 'pmt2.png', 'pmt3.png'],
    },
    {
      name: 'EXTA Lead',
      description: 'Informational landing page for a lead generation client with a centralized contact form built with Formspree, routing inquiries directly to the client\'s inbox — no backend required.',
      tags: ['HTML', 'Tailwind', 'JavaScript', 'Formspree'],
      url: 'https://extalead.info',
      type: 'Freelance',
      images: ['exta1.png', 'exta2.png'],
    },
    {
      name: 'Costa Rica Medical Trip',
      description: 'University capstone project — an appointment booking system for medical clinics across Costa Rica. Displays clinic profiles and specialist doctors with a full booking flow. Built with .NET Razor Pages, Blazor, and SQL Server, hosted on Azure.',
      tags: ['.NET', 'Razor Pages', 'Blazor', 'SQL Server', 'Azure'],
      url: '',
      type: 'University Project',
      images: ['medical1.jpeg', 'medical2.jpeg', 'medical3.jpeg'],
    }
  ],

  skills: [
    { category: 'Frontend & UI', items: ['HTML', 'CSS', 'JavaScript', 'Vue 3', 'React', 'Tailwind', 'Bootstrap', 'Webflow', 'Axios'] },
    { category: 'UI/UX Design', items: ['Figma', 'Wireframing', 'Prototyping', 'Design Systems', 'Handoff'] },
    { category: 'Business Intelligence', items: ['Power BI', 'DAX', 'Oracle BI', 'Excel', 'Pentaho ETL', 'Python', 'R'] },
    { category: 'Backend & APIs', items: ['REST APIs', 'NestJS', 'ASP.NET Core', 'Flask'] },
    { category: 'Cloud & DevOps', items: ['AWS S3', 'CloudFront', 'RDS', 'Docker', 'CI/CD'] },
    { category: 'AI & Tools', items: ['Claude', 'Stitch', 'AI-assisted dev'] },
    { category: 'Databases', items: ['MySQL', 'SQL Server', 'MongoDB', 'Oracle'] },
    { category: 'Version Control', items: ['Git', 'GitHub', 'Bitbucket', 'Jira', 'Scrum'] },
  ],

  certifications: [
    { name: 'Scrum Fundamentals Certified', issuer: 'SCRUMstudy' },
    { name: 'Huawei Cloud Certified Developer Professional (HCCDP)', issuer: 'Huawei' },
    { name: 'Huawei Cloud Certified Developer Associate (HCCDA)', issuer: 'Huawei' },
    { name: 'Cisco IT Essentials', issuer: 'Cisco' },
    { name: 'CCNAv7: Introduction to Networks', issuer: 'Cisco' },
    { name: 'CCNAv7: Switching, Routing and Wireless', issuer: 'Cisco' },
    { name: 'CCNAv7: Enterprise Networks, Security and Automation', issuer: 'Cisco' },
    { name: 'English B2+ (Fluent)', issuer: 'Sykes Academy' },
  ],
}
